language: elixir
otp_release:
  - 17.4
notifications:
  recipients:
    - ricn@rny.io
before_install:
  - sudo apt-get install pdf2htmlex
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
after_success:
  - "mix compile && mix coveralls.travis"
